# .codeclimate.yml
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  reek:
    enabled: true
  foodcritic:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
  - "**.md"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
